version: '3'

services:

  redis:
    image: redis
    ports:
      - "6379:6379"

  dashboard:
    build: ./dashboard
    ports:
      - "8050:8050"
    depends_on:
      - redis

  cmw_subscriber:
    build: ./cmw_subscriber
    depends_on:
      - redis
